---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: rust:1-slim
  commands:
  - apt-get update -y
  - apt-get install -y wget
  - wget -O sccache.tar.gz https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - tar zxvf sccache.tar.gz
  - export RUSTC_WRAPPER=$(pwd)/sccache-0.2.13-x86_64-unknown-linux-musl/sccache
  - export RUST_LOG=debug
  - cargo test
  - $(pwd)/sccache-0.2.13-x86_64-unknown-linux-musl/sccache --show-stats
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: sccache_s3_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: sccache_s3_secret_key
    SCCACHE_BUCKET: cache
    SCCACHE_ENDPOINT:
      from_secret: sccache_s3_endpoint
    SCCACHE_S3_USE_SSL: true

...
