[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"

regex = "1"
lazy_static = "1"

hex = "0.4"
md5 = "0.7"
